---
name: CI Build

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Save current weather condition
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          FILE=./assets/data/`date +"%Y%m%d"`.json
          echo "Begin to get today's weather condition."
          url="https://api.openweathermap.org/data/2.5/weather?id=1269843&units=metric&appid="$API_KEY
          response=$(curl -f "$url")
          status=$?
          if [ $status -eq 0 ]; then
              echo $response > $FILE
              echo "$FILE saved."
              echo `date +"%Y%m%d"` >> ./assets/data.txt
          else
              echo "curl exit code: ($status) $response"
              exit $status
          fi

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: git check in
        env:
          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config user.email "$GIT_OWNER_EMAIL"
          git config user.name "KD Puvvadi"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -S -am "add weather data `date +"%Y%m%d"`"
            git remote rm origin
            git remote add origin https://kdpuvvadi:$PUSH_TOKEN@github.com/kdpuvvadi/historical-weather-hyderabad.git
            git push origin HEAD:${GITHUB_REF##*/}
          else
            echo 'Nothing to do.'
          fi
